apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "$http_origin"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 10000m
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  labels:
    app: ingress
spec:
  ingressClassName: nginx
  rules:
    - host: dtech.enea.it
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: directus
                port:
                  number: 8055
    - host: model.dtech.enea.it
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: aton
                port:
                  number: 8070
    - host: viewer.dtech.enea.it
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: threedhop
                port:
                  number: 8080
