apiVersion: v1
kind: Service
metadata:
  name: svc-metallb
  namespace: ingress
spec:
  selector:
    name: nginx-ingress-microk8s
  type: LoadBalancer
  # loadBalancerIP is optional. MetalLB will automatically allocate an IP
  # from its pool if not specified. You can also specify one manually.
  # loadBalancerIP: 10.0.10.30
  # loadBalancerIP: 10.0.11.11
  loadBalancerIP: 192.168.18.236
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
